export const productsData = [
  {
    id: 1,
    name: "Product A",
    category: "Electronics",
    price: 599.99,
    stock: 50,
  },
  {
    id: 2,
    name: "Product B",
    category: "Clothing",
    price: 39.99,
    stock: 100,
  },
  {
    id: 3,
    name: "Product C",
    category: "Home & Kitchen",
    price: 149.99,
    stock: 30,
  },
  {
    id: 4,
    name: "Product D",
    category: "Books",
    price: 19.99,
    stock: 80,
  },
  {
    id: 5,
    name: "Product E",
    category: "Sports & Outdoors",
    price: 79.99,
    stock: 60,
  },
  {
    id: 6,
    name: "Product F",
    category: "Beauty & Personal Care",
    price: 29.99,
    stock: 90,
  },
  {
    id: 7,
    name: "Product G",
    category: "Toys & Games",
    price: 49.99,
    stock: 40,
  },
  {
    id: 8,
    name: "Product H",
    category: "Automotive",
    price: 129.99,
    stock: 20,
  },
  {
    id: 9,
    name: "Product I",
    category: "Tools & Home Improvement",
    price: 89.99,
    stock: 70,
  },
  {
    id: 10,
    name: "Product J",
    category: "Health & Household",
    price: 59.99,
    stock: 10,
  },
];

export const ordersData = [
  {
    id: 101,
    customerName: "Aeiswarja Biswas",
    orderDate: "2024-03-10",
    status: "Processing",
  },
  {
    id: 102,
    customerName: "Ram Yadav",
    orderDate: "2024-03-11",
    status: "Shipped",
  },
  {
    id: 103,
    customerName: "Mr Bean",
    orderDate: "2024-03-12",
    status: "Delivered",
  },
  {
    id: 104,
    customerName: "Bob Williams",
    orderDate: "2024-03-12",
    status: "Processing",
  },
  {
    id: 105,
    customerName: "Aeiswarja Yadav",
    orderDate: "2024-03-13",
    status: "Shipped",
  },
  {
    id: 106,
    customerName: "R Tagore",
    orderDate: "2024-03-14",
    status: "Processing",
  },
  {
    id: 107,
    customerName: "Avinash Yadav",
    orderDate: "2024-03-15",
    status: "Delivered",
  },
  {
    id: 108,
    customerName: "Grace Wilson",
    orderDate: "2024-03-15",
    status: "Processing",
  },
  {
    id: 109,
    customerName: "Harry White",
    orderDate: "2024-03-16",
    status: "Shipped",
  },
  {
    id: 110,
    customerName: "A Kumar",
    orderDate: "2024-03-17",
    status: "Processing",
  },
];
